### ISSUE TITLE
The Blahaj doesn't drop itself when mined with an empty hand. (1.19.2, Fabric, 0.3.1)

### ISSUE THREAD

**Issue by melechdaviid** [DaFuqs/Blahaj#1]
In survival mode, place down a Blahaj, and try to pick it back up with an empty hand (haven't tried shears). You _will be sad_ when it disappears.

**Comment by melechdaviid** [comment]
Correction: ALL of the plushies added by this mod have this behavior!

**Comment by DaFuqs** [comment]
Oh yeah, totally forgot to close this.
Fixed in v0.3.2, thank you!
