### ISSUE TITLE
ForgingScreenHandlerMixin is marked clientside, but is extended by commonside anvilscreenhandlermixin

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Blahaj#2]
https://github.com/DaFuqs/Blahaj/blob/b134f0034f7675008ee162a3a8c3fb7fd80bd80d/platform-fabric-1.19/src/main/resources/blahaj.mixins.json#L11

Issue persists on each version so they will all need to be fixed

**Comment by DaFuqs** [comment]
Indeed. Ty!
